import math

SINGLES_LINE_WIDTH = 8.22
DOUBLES_LINE_WIDTH = 10.97
HALF_COURT_DEPTH = 11.88
SERVICE_LINE_DEPTH = 6.4
DOUBLES_ALLEY_WIDTH = 1.37
NO_MANS_LAND_DEPTH = 5.48
RUN_BACK_DEPTH = 4.1
SIDE_RUN_WIDTH = 2.3
CENTER_LINE_DEPTH = 0.1
NET_CENTRE_HEIGHT = 0.91

REFERENCE_COURT_MARGIN_X = 50
REFERENCE_COURT_MARGIN_Y = 50

BALL_HEIGHT_OFFSET = 90

STATS_MARGIN_X = 50
STATS_MARGIN_Y = 50

BALL_RADIUS = 0.033
BALL_DRAG_COEFFICIENT = 0.6
AIR_DENSITY = 1.225
BALL_CROSS_SECTION = math.pi * BALL_RADIUS ** 2
BALL_MASS = 0.057
BALL_DRAG_FACTOR = AIR_DENSITY * BALL_DRAG_COEFFICIENT * BALL_CROSS_SECTION
GRAVITY = 9.8
BALL_TERMINAL_VELOCITY = ((2 * BALL_MASS * GRAVITY) / (BALL_DRAG_COEFFICIENT * AIR_DENSITY * BALL_CROSS_SECTION)) ** 0.5
BALL_TERMINAL_VELOCITY_SQUARED = BALL_TERMINAL_VELOCITY ** 2
DEFAULT_VERTICAL_VELOCITY = 3.0

PRE_TRAINED_MODEL_IMAGE_SIZE = 224
COURT_KEYPOINTS = 14

BALL_UNKNOWN     = -1
BALL_FAR_HIT     = 0
BALL_NEAR_BOUNCE = 1
BALL_NEAR_HIT    = 2
BALL_FAR_BOUNCE  = 3
BALL_IN_FLIGHT   = 4
BALL_DEAD        = 5

PLAYER_UNKNOWN = -1
PLAYER_RUN = 0
PLAYER_HIT = 1

